<?php

namespace Tests\Feature\SuperAdmin;

use App\Models\CmsPage;
use Inertia\Testing\AssertableInertia as Assert;

class CmsTest extends SuperAdminTestCase
{
    // ---- Pages ----

    public function test_pages_index_renders(): void
    {
        $this->get(route('superadmin.cms.pages.index'))
            ->assertOk()
            ->assertInertia(fn (Assert $page) => $page->component('superadmin/cms/pages/index'));
    }

    public function test_can_create_page_with_autogenerated_slug(): void
    {
        $this->post(route('superadmin.cms.pages.store'), [
            'title' => 'About the Platform',
            'content' => 'Some content',
            'status' => 'published',
            'sort_order' => 0,
        ])->assertRedirect(route('superadmin.cms.pages.index'));

        $this->assertDatabaseHas('cms_pages', [
            'title' => 'About the Platform',
            'slug' => 'about-the-platform',
            'status' => 'published',
        ]);
    }

    public function test_create_page_requires_title(): void
    {
        $this->post(route('superadmin.cms.pages.store'), [
            'status' => 'draft',
        ])->assertSessionHasErrors('title');
    }

    public function test_can_update_page_and_generate_unique_slug(): void
    {
        $page = CmsPage::firstOrCreate(
            ['slug' => 'existing'],
            ['title' => 'Existing', 'content' => 'x', 'status' => 'draft', 'sort_order' => 0]
        );

        $this->put(route('superadmin.cms.pages.update', $page), [
            'title' => 'Existing',
            'slug' => 'existing',
            'status' => 'published',
            'sort_order' => 0,
        ])->assertRedirect(route('superadmin.cms.pages.index'));

        $this->assertDatabaseHas('cms_pages', [
            'id' => $page->id,
            'status' => 'published',
        ]);
    }

    public function test_can_delete_page(): void
    {
        $page = CmsPage::create([
            'title' => 'Disposable',
            'slug' => 'disposable',
            'status' => 'draft',
            'sort_order' => 0,
        ]);

        $this->delete(route('superadmin.cms.pages.destroy', $page))
            ->assertRedirect(route('superadmin.cms.pages.index'));

        $this->assertDatabaseMissing('cms_pages', ['id' => $page->id]);
    }

    // ---- Sections ----

    public function test_sections_index_renders(): void
    {
        $this->get(route('superadmin.cms.sections.index'))
            ->assertOk()
            ->assertInertia(fn (Assert $page) => $page->component('superadmin/cms/sections/index'));
    }

    public function test_can_create_section(): void
    {
        $this->post(route('superadmin.cms.sections.store'), [
            'name' => 'Pricing Section',
            'section_type' => 'pricing',
            'heading' => 'Simple pricing',
            'status' => 'published',
            'sort_order' => 4,
        ])->assertRedirect(route('superadmin.cms.sections.index'));

        $this->assertDatabaseHas('cms_sections', [
            'slug' => 'pricing-section',
            'section_type' => 'pricing',
        ]);
    }

    public function test_section_requires_valid_type(): void
    {
        $this->post(route('superadmin.cms.sections.store'), [
            'name' => 'Bad',
            'section_type' => 'not-a-type',
            'status' => 'draft',
        ])->assertSessionHasErrors('section_type');
    }

    // ---- Blog ----

    public function test_blog_index_renders(): void
    {
        $this->get(route('superadmin.blog.posts.index'))
            ->assertOk()
            ->assertInertia(fn (Assert $page) => $page->component('superadmin/blog/posts/index'));
    }

    public function test_can_create_blog_post(): void
    {
        $this->post(route('superadmin.blog.posts.store'), [
            'title' => 'Welcome to the platform',
            'body' => 'Hello world',
            'status' => 'published',
            'category' => 'News',
        ])->assertRedirect(route('superadmin.blog.posts.index'));

        $this->assertDatabaseHas('blog_posts', [
            'title' => 'Welcome to the platform',
            'slug' => 'welcome-to-the-platform',
            'status' => 'published',
        ]);
    }

    public function test_blog_post_requires_body(): void
    {
        $this->post(route('superadmin.blog.posts.store'), [
            'title' => 'Missing body',
            'status' => 'draft',
        ])->assertSessionHasErrors('body');
    }
}
